# Site settings
title: NaiveText
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  NaiveText is a text classifier gem written in Ruby and made to be easily integratable into your rails app.
baseurl: "/NaiveText" # the subpath of your site, e.g. /blog/
url: "http://ricciflowing.github.io/" # the base hostname & protocol for your site
twitter_username: ricciflowing
github_username:  ricciflowing

# Build settings
markdown: redcarpet
