# Site settings
title: NaiveText
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  NaiveText is a text classifier gem written in Ruby and made easily integratable into your rails app.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ricciflowing
github_username:  ricciflowing

# Build settings
markdown: kramdown
